<?php
/**
 * AUTO-GENERATED by scripts/generate-control-index.mjs -- DO NOT EDIT
 *
 * Maps element controls to CSS properties for the HTML-to-Bricks converter.
 * Contains ONLY the fields needed at runtime: type, css (property, selector).
 *
 * Regenerate with:
 *   node scripts/generate-control-index.mjs
 *
 * @since 2.4
 * @package Bricks
 */

namespace Bricks;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Control index for HTML to Bricks CSS control mapping.
 *
 * @since 2.4
 */
class Html_To_Bricks_Control_Index {
	/**
	 * Layout element names.
	 *
	 * @since 2.4
	 * @var array
	 */
	private static $layout_elements = [ 'section', 'container', 'block', 'div' ];

	/**
	 * Get inherited controls shared by all elements.
	 *
	 * Only controls with CSS mappings are included.
	 *
	 * @since 2.4
	 *
	 * @return array Inherited controls indexed by control key.
	 */
	public static function get_inherited_controls() {
		return [
			'_margin'                        => [
				'type' => 'spacing',
				'css'  => [ [ 'property' => 'margin' ] ],
			],
			'_padding'                       => [
				'type' => 'spacing',
				'css'  => [ [ 'property' => 'padding' ] ],
			],
			'_width'                         => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'width' ] ],
			],
			'_widthMin'                      => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'min-width' ] ],
			],
			'_widthMax'                      => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'max-width' ] ],
			],
			'_height'                        => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'height' ] ],
			],
			'_heightMin'                     => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'min-height' ] ],
			],
			'_heightMax'                     => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'max-height' ] ],
			],
			'_aspectRatio'                   => [
				'type' => 'text',
				'css'  => [ [ 'property' => 'aspect-ratio' ] ],
			],
			'_position'                      => [
				'type' => 'select',
				'css'  => [ [ 'property' => 'position' ] ],
			],
			'_top'                           => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'top' ] ],
			],
			'_right'                         => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'right' ] ],
			],
			'_bottom'                        => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'bottom' ] ],
			],
			'_left'                          => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'left' ] ],
			],
			'_zIndex'                        => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'z-index' ] ],
			],
			'_order'                         => [
				'type'         => 'number',
				'css'          => [ [ 'property' => 'order' ] ],
				'elementScope' => 'nonLayout',
			],
			'_display'                       => [
				'type'         => 'select',
				'css'          => [ [ 'property' => 'display' ] ],
				'elementScope' => 'nonLayout',
			],
			'_visibility'                    => [
				'type' => 'select',
				'css'  => [ [ 'property' => 'visibility' ] ],
			],
			'_overflow'                      => [
				'type' => 'text',
				'css'  => [ [ 'property' => 'overflow' ] ],
			],
			'_opacity'                       => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'opacity' ] ],
			],
			'_cursor'                        => [
				'type' => 'select',
				'css'  => [ [ 'property' => 'cursor' ] ],
			],
			'_isolation'                     => [
				'type' => 'select',
				'css'  => [ [ 'property' => 'isolation' ] ],
			],
			'_mixBlendMode'                  => [
				'type' => 'select',
				'css'  => [ [ 'property' => 'mix-blend-mode' ] ],
			],
			'_pointerEvents'                 => [
				'type' => 'text',
				'css'  => [ [ 'property' => 'pointer-events' ] ],
			],
			'_perspective'                   => [
				'type' => 'number',
				'css'  => [ [ 'property' => 'perspective' ] ],
			],
			'_perspectiveOrigin'             => [
				'type' => 'text',
				'css'  => [ [ 'property' => 'perspective-origin' ] ],
			],
			'_gridItemJustifySelf'           => [
				'type'         => 'align-items',
				'css'          => [ [ 'property' => 'justify-self' ] ],
				'elementScope' => 'nonLayout',
			],
			'_flexDirection'                 => [
				'type'         => 'direction',
				'css'          => [ [ 'property' => 'flex-direction' ] ],
				'elementScope' => 'nonLayout',
			],
			'_alignSelf'                     => [
				'type'         => 'align-items',
				'css'          => [ [ 'property' => 'align-self' ] ],
				'elementScope' => 'nonLayout',
			],
			'_justifyContent'                => [
				'type'         => 'justify-content',
				'css'          => [ [ 'property' => 'justify-content' ] ],
				'elementScope' => 'nonLayout',
			],
			'_alignItems'                    => [
				'type'         => 'align-items',
				'css'          => [ [ 'property' => 'align-items' ] ],
				'elementScope' => 'nonLayout',
			],
			'_gap'                           => [
				'type'         => 'number',
				'css'          => [ [ 'property' => 'gap' ] ],
				'elementScope' => 'nonLayout',
			],
			'_flexGrow'                      => [
				'type'         => 'number',
				'css'          => [ [ 'property' => 'flex-grow' ] ],
				'elementScope' => 'nonLayout',
			],
			'_flexShrink'                    => [
				'type'         => 'number',
				'css'          => [ [ 'property' => 'flex-shrink' ] ],
				'elementScope' => 'nonLayout',
			],
			'_flexBasis'                     => [
				'type'         => 'text',
				'css'          => [ [ 'property' => 'flex-basis' ] ],
				'elementScope' => 'nonLayout',
			],
			'_masonryColumn'                 => [
				'type' => 'number',
				'css'  => [ [ 'property' => '--columns' ] ],
			],
			'_masonryGutter'                 => [
				'type' => 'number',
				'css'  => [ [ 'property' => '--gutter' ] ],
			],
			'_typography'                    => [
				'type' => 'typography',
				'css'  => [ [ 'property' => 'font' ] ],
			],
			'_background'                    => [
				'type' => 'background',
				'css'  => [ [ 'property' => 'background' ] ],
			],
			'_gradient'                      => [
				'type' => 'gradient',
				'css'  => [ [ 'property' => 'background-image' ] ],
			],
			'_border'                        => [
				'type' => 'border',
				'css'  => [ [ 'property' => 'border' ] ],
			],
			'_boxShadow'                     => [
				'type' => 'box-shadow',
				'css'  => [ [ 'property' => 'box-shadow' ] ],
			],
			'_transform'                     => [
				'type' => 'transform',
				'css'  => [ [ 'property' => 'transform' ] ],
			],
			'_transformOrigin'               => [
				'type' => 'text',
				'css'  => [ [ 'property' => 'transform-origin' ] ],
			],
			'_motionElementParallaxSpeedX'   => [
				'type' => 'number',
				'css'  => [ [ 'property' => '--brx-motion-parallax-speed-x' ] ],
			],
			'_motionElementParallaxSpeedY'   => [
				'type' => 'number',
				'css'  => [ [ 'property' => '--brx-motion-parallax-speed-y' ] ],
			],
			'_motionBackgroundParallaxSpeed' => [
				'type' => 'number',
				'css'  => [ [ 'property' => '--brx-motion-background-speed' ] ],
			],
			'_cssFilters'                    => [
				'type' => 'filters',
				'css'  => [ [ 'property' => 'filter' ] ],
			],
			'_cssTransition'                 => [
				'type' => 'text',
				'css'  => [ [ 'property' => 'transition' ] ],
			],
			'_scrollSnapType'                => [
				'type' => 'select',
				'css'  => [
					[
						'property' => 'scroll-snap-type',
						'selector' => 'html',
					],
				],
			],
			'_scrollSnapAlign'               => [
				'type' => 'select',
				'css'  => [
					[
						'property' => 'scroll-snap-align',
						'selector' => '.brxe-section',
					],
				],
			],
			'_scrollSnapStop'                => [
				'type' => 'select',
				'css'  => [
					[
						'property' => 'scroll-snap-stop',
						'selector' => '.brxe-section',
					],
				],
			],
		];
	}

	/**
	 * Get element-specific controls indexed by element name.
	 *
	 * Only elements with CSS-mapped controls are included.
	 *
	 * @since 2.4
	 *
	 * @return array Element controls indexed by element name then control key.
	 */
	public static function get_element_controls() {
		return [
			'section'   => [
				'_gridItemColumnSpan'  => [
					'type' => 'text',
					'css'  => [ [ 'property' => 'grid-column' ] ],
				],
				'_gridItemRowSpan'     => [
					'type' => 'text',
					'css'  => [ [ 'property' => 'grid-row' ] ],
				],
				'_gridItemJustifySelf' => [
					'type' => 'align-items',
					'css'  => [ [ 'property' => 'justify-self' ] ],
				],
				'_display'             => [
					'type' => 'select',
					'css'  => [ [ 'property' => 'display' ] ],
				],
				'_gridGap'             => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'grid-gap' ] ],
					'hasRequired' => true,
				],
				'_gridTemplateColumns' => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-template-columns' ] ],
					'hasRequired' => true,
				],
				'_gridTemplateRows'    => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-template-rows' ] ],
					'hasRequired' => true,
				],
				'_gridAutoColumns'     => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-auto-columns' ] ],
					'hasRequired' => true,
				],
				'_gridAutoRows'        => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-auto-rows' ] ],
					'hasRequired' => true,
				],
				'_gridAutoFlow'        => [
					'type'        => 'select',
					'css'         => [ [ 'property' => 'grid-auto-flow' ] ],
					'hasRequired' => true,
				],
				'_justifyItemsGrid'    => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-items' ] ],
					'hasRequired' => true,
				],
				'_alignItemsGrid'      => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-items' ] ],
					'hasRequired' => true,
				],
				'_justifyContentGrid'  => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-content' ] ],
					'hasRequired' => true,
				],
				'_alignContentGrid'    => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-content' ] ],
					'hasRequired' => true,
				],
				'_flexWrap'            => [
					'type'        => 'select',
					'css'         => [ [ 'property' => 'flex-wrap' ] ],
					'hasRequired' => true,
				],
				'_direction'           => [
					'type'        => 'direction',
					'css'         => [ [ 'property' => 'flex-direction' ] ],
					'hasRequired' => true,
				],
				'_alignSelf'           => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-self' ] ],
					'hasRequired' => true,
				],
				'_justifyContent'      => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-content' ] ],
					'hasRequired' => true,
				],
				'_alignItems'          => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-items' ] ],
					'hasRequired' => true,
				],
				'_columnGap'           => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'column-gap' ] ],
					'hasRequired' => true,
				],
				'_rowGap'              => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'row-gap' ] ],
					'hasRequired' => true,
				],
				'_flexGrow'            => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'flex-grow' ] ],
					'hasRequired' => true,
				],
				'_flexShrink'          => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'flex-shrink' ] ],
					'hasRequired' => true,
				],
				'_flexBasis'           => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'flex-basis' ] ],
					'hasRequired' => true,
				],
				'_order'               => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'order' ] ],
					'hasRequired' => true,
				],
			],
			'container' => [
				'_gridItemColumnSpan'  => [
					'type' => 'text',
					'css'  => [ [ 'property' => 'grid-column' ] ],
				],
				'_gridItemRowSpan'     => [
					'type' => 'text',
					'css'  => [ [ 'property' => 'grid-row' ] ],
				],
				'_gridItemJustifySelf' => [
					'type' => 'align-items',
					'css'  => [ [ 'property' => 'justify-self' ] ],
				],
				'_display'             => [
					'type' => 'select',
					'css'  => [ [ 'property' => 'display' ] ],
				],
				'_gridGap'             => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'grid-gap' ] ],
					'hasRequired' => true,
				],
				'_gridTemplateColumns' => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-template-columns' ] ],
					'hasRequired' => true,
				],
				'_gridTemplateRows'    => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-template-rows' ] ],
					'hasRequired' => true,
				],
				'_gridAutoColumns'     => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-auto-columns' ] ],
					'hasRequired' => true,
				],
				'_gridAutoRows'        => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-auto-rows' ] ],
					'hasRequired' => true,
				],
				'_gridAutoFlow'        => [
					'type'        => 'select',
					'css'         => [ [ 'property' => 'grid-auto-flow' ] ],
					'hasRequired' => true,
				],
				'_justifyItemsGrid'    => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-items' ] ],
					'hasRequired' => true,
				],
				'_alignItemsGrid'      => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-items' ] ],
					'hasRequired' => true,
				],
				'_justifyContentGrid'  => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-content' ] ],
					'hasRequired' => true,
				],
				'_alignContentGrid'    => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-content' ] ],
					'hasRequired' => true,
				],
				'_flexWrap'            => [
					'type'        => 'select',
					'css'         => [ [ 'property' => 'flex-wrap' ] ],
					'hasRequired' => true,
				],
				'_direction'           => [
					'type'        => 'direction',
					'css'         => [ [ 'property' => 'flex-direction' ] ],
					'hasRequired' => true,
				],
				'_alignSelf'           => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-self' ] ],
					'hasRequired' => true,
				],
				'_justifyContent'      => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-content' ] ],
					'hasRequired' => true,
				],
				'_alignItems'          => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-items' ] ],
					'hasRequired' => true,
				],
				'_columnGap'           => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'column-gap' ] ],
					'hasRequired' => true,
				],
				'_rowGap'              => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'row-gap' ] ],
					'hasRequired' => true,
				],
				'_flexGrow'            => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'flex-grow' ] ],
					'hasRequired' => true,
				],
				'_flexShrink'          => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'flex-shrink' ] ],
					'hasRequired' => true,
				],
				'_flexBasis'           => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'flex-basis' ] ],
					'hasRequired' => true,
				],
				'_order'               => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'order' ] ],
					'hasRequired' => true,
				],
			],
			'block'     => [
				'_gridItemColumnSpan'  => [
					'type' => 'text',
					'css'  => [ [ 'property' => 'grid-column' ] ],
				],
				'_gridItemRowSpan'     => [
					'type' => 'text',
					'css'  => [ [ 'property' => 'grid-row' ] ],
				],
				'_gridItemJustifySelf' => [
					'type' => 'align-items',
					'css'  => [ [ 'property' => 'justify-self' ] ],
				],
				'_display'             => [
					'type' => 'select',
					'css'  => [ [ 'property' => 'display' ] ],
				],
				'_gridGap'             => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'grid-gap' ] ],
					'hasRequired' => true,
				],
				'_gridTemplateColumns' => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-template-columns' ] ],
					'hasRequired' => true,
				],
				'_gridTemplateRows'    => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-template-rows' ] ],
					'hasRequired' => true,
				],
				'_gridAutoColumns'     => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-auto-columns' ] ],
					'hasRequired' => true,
				],
				'_gridAutoRows'        => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-auto-rows' ] ],
					'hasRequired' => true,
				],
				'_gridAutoFlow'        => [
					'type'        => 'select',
					'css'         => [ [ 'property' => 'grid-auto-flow' ] ],
					'hasRequired' => true,
				],
				'_justifyItemsGrid'    => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-items' ] ],
					'hasRequired' => true,
				],
				'_alignItemsGrid'      => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-items' ] ],
					'hasRequired' => true,
				],
				'_justifyContentGrid'  => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-content' ] ],
					'hasRequired' => true,
				],
				'_alignContentGrid'    => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-content' ] ],
					'hasRequired' => true,
				],
				'_flexWrap'            => [
					'type'        => 'select',
					'css'         => [ [ 'property' => 'flex-wrap' ] ],
					'hasRequired' => true,
				],
				'_direction'           => [
					'type'        => 'direction',
					'css'         => [ [ 'property' => 'flex-direction' ] ],
					'hasRequired' => true,
				],
				'_alignSelf'           => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-self' ] ],
					'hasRequired' => true,
				],
				'_justifyContent'      => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-content' ] ],
					'hasRequired' => true,
				],
				'_alignItems'          => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-items' ] ],
					'hasRequired' => true,
				],
				'_columnGap'           => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'column-gap' ] ],
					'hasRequired' => true,
				],
				'_rowGap'              => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'row-gap' ] ],
					'hasRequired' => true,
				],
				'_flexGrow'            => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'flex-grow' ] ],
					'hasRequired' => true,
				],
				'_flexShrink'          => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'flex-shrink' ] ],
					'hasRequired' => true,
				],
				'_flexBasis'           => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'flex-basis' ] ],
					'hasRequired' => true,
				],
				'_order'               => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'order' ] ],
					'hasRequired' => true,
				],
			],
			'div'       => [
				'_gridItemColumnSpan'  => [
					'type' => 'text',
					'css'  => [ [ 'property' => 'grid-column' ] ],
				],
				'_gridItemRowSpan'     => [
					'type' => 'text',
					'css'  => [ [ 'property' => 'grid-row' ] ],
				],
				'_gridItemJustifySelf' => [
					'type' => 'align-items',
					'css'  => [ [ 'property' => 'justify-self' ] ],
				],
				'_display'             => [
					'type' => 'select',
					'css'  => [ [ 'property' => 'display' ] ],
				],
				'_gridGap'             => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'grid-gap' ] ],
					'hasRequired' => true,
				],
				'_gridTemplateColumns' => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-template-columns' ] ],
					'hasRequired' => true,
				],
				'_gridTemplateRows'    => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-template-rows' ] ],
					'hasRequired' => true,
				],
				'_gridAutoColumns'     => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-auto-columns' ] ],
					'hasRequired' => true,
				],
				'_gridAutoRows'        => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'grid-auto-rows' ] ],
					'hasRequired' => true,
				],
				'_gridAutoFlow'        => [
					'type'        => 'select',
					'css'         => [ [ 'property' => 'grid-auto-flow' ] ],
					'hasRequired' => true,
				],
				'_justifyItemsGrid'    => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-items' ] ],
					'hasRequired' => true,
				],
				'_alignItemsGrid'      => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-items' ] ],
					'hasRequired' => true,
				],
				'_justifyContentGrid'  => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-content' ] ],
					'hasRequired' => true,
				],
				'_alignContentGrid'    => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-content' ] ],
					'hasRequired' => true,
				],
				'_flexWrap'            => [
					'type'        => 'select',
					'css'         => [ [ 'property' => 'flex-wrap' ] ],
					'hasRequired' => true,
				],
				'_direction'           => [
					'type'        => 'direction',
					'css'         => [ [ 'property' => 'flex-direction' ] ],
					'hasRequired' => true,
				],
				'_alignSelf'           => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-self' ] ],
					'hasRequired' => true,
				],
				'_justifyContent'      => [
					'type'        => 'justify-content',
					'css'         => [ [ 'property' => 'justify-content' ] ],
					'hasRequired' => true,
				],
				'_alignItems'          => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-items' ] ],
					'hasRequired' => true,
				],
				'_columnGap'           => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'column-gap' ] ],
					'hasRequired' => true,
				],
				'_rowGap'              => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'row-gap' ] ],
					'hasRequired' => true,
				],
				'_flexGrow'            => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'flex-grow' ] ],
					'hasRequired' => true,
				],
				'_flexShrink'          => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'flex-shrink' ] ],
					'hasRequired' => true,
				],
				'_flexBasis'           => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'flex-basis' ] ],
					'hasRequired' => true,
				],
				'_order'               => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'order' ] ],
					'hasRequired' => true,
				],
			],
			'heading'   => [
				'separatorWidth'      => [
					'type' => 'number',
					'css'  => [
						[
							'property' => 'width',
							'selector' => '.separator',
						],
						[
							'property' => 'flex-grow',
							'selector' => '.separator',
						],
					],
				],
				'separatorHeight'     => [
					'type' => 'number',
					'css'  => [
						[
							'property' => 'border-top-width',
							'selector' => '.separator',
						],
						[
							'property' => 'height',
							'selector' => '.separator',
						],
					],
				],
				'separatorSpacing'    => [
					'type' => 'number',
					'css'  => [
						[
							'property' => 'gap',
							'selector' => '&.has-separator',
						],
					],
				],
				'separatorStyle'      => [
					'type' => 'select',
					'css'  => [
						[
							'property' => 'border-top-style',
							'selector' => '.separator',
						],
					],
				],
				'separatorAlignItems' => [
					'type' => 'align-items',
					'css'  => [
						[
							'property' => 'align-items',
							'selector' => '&.has-separator',
						],
					],
				],
				'separatorColor'      => [
					'type' => 'color',
					'css'  => [
						[
							'property' => 'border-top-color',
							'selector' => '.separator',
						],
					],
				],
			],
			'text-link' => [
				'icon'           => [
					'type' => 'icon',
					'css'  => [
						[
							'property' => null,
							'selector' => '.icon > svg',
						],
					],
				],
				'iconSize'       => [
					'type'        => 'number',
					'css'         => [
						[
							'property' => 'font-size',
							'selector' => '.icon > i',
						],
						[
							'property' => 'width',
							'selector' => '.icon > svg',
						],
						[
							'property' => 'height',
							'selector' => '.icon > svg',
						],
					],
					'hasRequired' => true,
				],
				'iconWidth'      => [
					'type'        => 'number',
					'css'         => [
						[
							'property' => 'width',
							'selector' => '.icon',
						],
					],
					'hasRequired' => true,
				],
				'iconHeight'     => [
					'type'        => 'number',
					'css'         => [
						[
							'property' => 'height',
							'selector' => '.icon',
						],
					],
					'hasRequired' => true,
				],
				'iconColor'      => [
					'type'        => 'color',
					'css'         => [
						[
							'property' => 'color',
							'selector' => '.icon',
						],
						[
							'property' => 'fill',
							'selector' => '.icon',
						],
					],
					'hasRequired' => true,
				],
				'iconBackground' => [
					'type'        => 'color',
					'css'         => [
						[
							'property' => 'background-color',
							'selector' => '.icon',
						],
					],
					'hasRequired' => true,
				],
				'iconBorder'     => [
					'type'        => 'border',
					'css'         => [
						[
							'property' => 'border',
							'selector' => '.icon',
						],
					],
					'hasRequired' => true,
				],
				'gap'            => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'gap' ] ],
					'hasRequired' => true,
				],
			],
			'icon'      => [
				'iconColor'                    => [
					'type'        => 'color',
					'css'         => [ [ 'property' => 'color' ], [ 'property' => 'fill' ] ],
					'hasRequired' => true,
				],
				'iconSize'                     => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'font-size' ] ],
					'hasRequired' => true,
				],
				'accordionTitleIconTransform'  => [
					'type'        => 'transform',
					'css'         => [ [ 'property' => '--brx-icon-transform' ] ],
					'hasRequired' => true,
				],
				'accordionTitleIconTransition' => [
					'type'        => 'text',
					'css'         => [ [ 'property' => 'transition' ] ],
					'hasRequired' => true,
				],
			],
			'button'    => [
				'iconTypography' => [
					'type'        => 'typography',
					'css'         => [
						[
							'property' => 'font',
							'selector' => 'i',
						],
					],
					'hasRequired' => true,
				],
				'iconGap'        => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'gap' ] ],
					'hasRequired' => true,
				],
			],
			'image'     => [
				'popupIconBackgroundColor' => [
					'type'        => 'color',
					'css'         => [
						[
							'property' => 'background-color',
							'selector' => '&{pseudo} .icon',
						],
					],
					'hasRequired' => true,
				],
				'popupIconBorder'          => [
					'type'        => 'border',
					'css'         => [
						[
							'property' => 'border',
							'selector' => '&{pseudo} .icon',
						],
					],
					'hasRequired' => true,
				],
				'popupIconBoxShadow'       => [
					'type'        => 'box-shadow',
					'css'         => [
						[
							'property' => 'box-shadow',
							'selector' => '&{pseudo} .icon',
						],
					],
					'hasRequired' => true,
				],
				'popupIconTypography'      => [
					'type'        => 'typography',
					'css'         => [
						[
							'property' => 'font',
							'selector' => '&{pseudo} .icon',
						],
					],
					'hasRequired' => true,
				],
				'popupIconHeight'          => [
					'type'        => 'number',
					'css'         => [
						[
							'property' => 'line-height',
							'selector' => '&{pseudo} .icon',
						],
					],
					'hasRequired' => true,
				],
				'popupIconWidth'           => [
					'type'        => 'number',
					'css'         => [
						[
							'property' => 'width',
							'selector' => '&{pseudo} .icon',
						],
					],
					'hasRequired' => true,
				],
				'popupIconTransition'      => [
					'type'        => 'text',
					'css'         => [
						[
							'property' => 'transition',
							'selector' => '&{pseudo} .icon',
						],
					],
					'hasRequired' => true,
				],
			],
			'svg'       => [
				'height'      => [
					'type' => 'number',
					'css'  => [ [ 'property' => 'height' ] ],
				],
				'width'       => [
					'type' => 'number',
					'css'  => [ [ 'property' => 'width' ] ],
				],
				'strokeWidth' => [
					'type' => 'number',
					'css'  => [
						[
							'property' => 'stroke-width',
							'selector' => '*',
						],
					],
				],
				'stroke'      => [
					'type' => 'color',
					'css'  => [
						[
							'property' => 'stroke',
							'selector' => ':not([stroke="none"])',
						],
					],
				],
				'fill'        => [
					'type' => 'color',
					'css'  => [
						[
							'property' => 'fill',
							'selector' => ':not([fill="none"])',
						],
					],
				],
			],
			'video'     => [
				'aspectRatio'                => [
					'type' => 'select',
					'css'  => [ [ 'property' => 'aspect-ratio' ] ],
				],
				'objectFit'                  => [
					'type'        => 'select',
					'css'         => [
						[
							'property' => 'object-fit',
							'selector' => 'video',
						],
					],
					'hasRequired' => true,
				],
				'overlay'                    => [
					'type' => 'background',
					'css'  => [
						[
							'property' => 'background',
							'selector' => '.bricks-video-overlay',
						],
					],
				],
				'overlayIconTypography'      => [
					'type'        => 'typography',
					'css'         => [
						[
							'property' => 'font',
							'selector' => '.bricks-video-overlay-icon',
						],
					],
					'hasRequired' => true,
				],
				'overlayIconPadding'         => [
					'type'        => 'spacing',
					'css'         => [
						[
							'property' => 'padding',
							'selector' => '.bricks-video-overlay-icon',
						],
					],
					'hasRequired' => true,
				],
				'overlayIconBackgroundColor' => [
					'type'        => 'color',
					'css'         => [
						[
							'property' => 'background-color',
							'selector' => '.bricks-video-overlay-icon',
						],
					],
					'hasRequired' => true,
				],
				'overlayIconBorder'          => [
					'type'        => 'border',
					'css'         => [
						[
							'property' => 'border',
							'selector' => '.bricks-video-overlay-icon',
						],
					],
					'hasRequired' => true,
				],
				'overlayIconBoxShadow'       => [
					'type'        => 'box-shadow',
					'css'         => [
						[
							'property' => 'box-shadow',
							'selector' => '.bricks-video-overlay-icon',
						],
					],
					'hasRequired' => true,
				],
			],
			'divider'   => [
				'height'         => [
					'type' => 'number',
					'css'  => [
						[
							'property' => 'height',
							'selector' => '.line',
						],
						[
							'property' => 'border-top-width',
							'selector' => '&.horizontal .line',
						],
					],
				],
				'width'          => [
					'type' => 'number',
					'css'  => [
						[
							'property' => 'width',
							'selector' => '&.horizontal .line',
						],
						[
							'property' => 'border-right-width',
							'selector' => '&.vertical .line',
						],
					],
				],
				'style'          => [
					'type' => 'select',
					'css'  => [
						[
							'property' => 'border-top-style',
							'selector' => '&.horizontal .line',
						],
						[
							'property' => 'border-right-style',
							'selector' => '&.vertical .line',
						],
					],
				],
				'justifyContent' => [
					'type' => 'justify-content',
					'css'  => [
						[
							'property' => 'justify-content',
							'selector' => '&.horizontal',
						],
						[
							'property' => 'align-self',
							'selector' => '&.vertical',
						],
					],
				],
				'color'          => [
					'type' => 'color',
					'css'  => [
						[
							'property' => 'border-top-color',
							'selector' => '&.horizontal .line',
						],
						[
							'property' => 'border-right-color',
							'selector' => '&.vertical .line',
						],
						[
							'property' => 'color',
							'selector' => '.icon',
						],
					],
				],
				'iconTypography' => [
					'type'        => 'typography',
					'css'         => [
						[
							'property' => 'font',
							'selector' => '.icon',
						],
					],
					'hasRequired' => true,
				],
				'iconAlignItems' => [
					'type'        => 'align-items',
					'css'         => [ [ 'property' => 'align-items' ] ],
					'hasRequired' => true,
				],
				'iconSpacing'    => [
					'type'        => 'number',
					'css'         => [ [ 'property' => 'gap' ] ],
					'hasRequired' => true,
				],
			],
			'form'      => [
				'fields'                      => [
					'type'        => 'repeater',
					'css'         => [
						[
							'property' => 'font',
							'selector' => '.password-toggle .show-password i',
						],
					],
					'hasRequired' => true,
				],
				'labelTypography'             => [
					'type'        => 'typography',
					'css'         => [
						[
							'property' => 'font',
							'selector' => 'label',
						],
						[
							'property' => 'font',
							'selector' => '.label',
						],
					],
					'hasRequired' => true,
				],
				'placeholderTypography'       => [
					'type' => 'typography',
					'css'  => [
						[
							'property' => 'font',
							'selector' => '::placeholder',
						],
						[
							'property' => 'font',
							'selector' => 'select',
						],
					],
				],
				'fieldMargin'                 => [
					'type' => 'spacing',
					'css'  => [
						[
							'property' => 'padding',
							'selector' => '.form-group:not(.submit-button-wrapper):not(.message):not(.captcha)',
						],
					],
				],
				'fieldPadding'                => [
					'type' => 'spacing',
					'css'  => [
						[
							'property' => 'padding',
							'selector' => '.form-group input',
						],
						[
							'property' => 'padding',
							'selector' => '.flatpickr',
						],
						[
							'property' => 'padding',
							'selector' => 'select',
						],
						[
							'property' => 'padding',
							'selector' => 'textarea',
						],
					],
				],
				'horizontalAlignFields'       => [
					'type' => 'justify-content',
					'css'  => [ [ 'property' => 'justify-content' ] ],
				],
				'fieldBackgroundColor'        => [
					'type' => 'color',
					'css'  => [
						[
							'property' => 'background-color',
							'selector' => '.form-group input',
						],
						[
							'property' => 'background-color',
							'selector' => '.flatpickr',
						],
						[
							'property' => 'background-color',
							'selector' => 'select',
						],
						[
							'property' => 'background-color',
							'selector' => 'textarea',
						],
					],
				],
				'fieldBorder'                 => [
					'type' => 'border',
					'css'  => [
						[
							'property' => 'border',
							'selector' => '.form-group input',
						],
						[
							'property' => 'border',
							'selector' => '.flatpickr',
						],
						[
							'property' => 'border',
							'selector' => 'select',
						],
						[
							'property' => 'border',
							'selector' => 'textarea',
						],
						[
							'property' => 'border',
							'selector' => '.bricks-button:not([type=submit])',
						],
						[
							'property' => 'border',
							'selector' => '.choose-files',
						],
					],
				],
				'fieldTypography'             => [
					'type' => 'typography',
					'css'  => [
						[
							'property' => 'font',
							'selector' => '.form-group input',
						],
						[
							'property' => 'font',
							'selector' => 'select',
						],
						[
							'property' => 'font',
							'selector' => 'textarea',
						],
					],
				],
				'submitButtonWidth'           => [
					'type'        => 'number',
					'css'         => [
						[
							'property' => 'width',
							'selector' => '.submit-button-wrapper',
						],
					],
					'hasRequired' => true,
				],
				'submitButtonMargin'          => [
					'type' => 'spacing',
					'css'  => [
						[
							'property' => 'margin',
							'selector' => '.submit-button-wrapper',
						],
					],
				],
				'submitButtonTypography'      => [
					'type' => 'typography',
					'css'  => [
						[
							'property' => 'font',
							'selector' => '.bricks-button',
						],
					],
				],
				'submitButtonBackgroundColor' => [
					'type' => 'color',
					'css'  => [
						[
							'property' => 'background-color',
							'selector' => '.bricks-button',
						],
					],
				],
				'submitButtonBorder'          => [
					'type' => 'border',
					'css'  => [
						[
							'property' => 'border',
							'selector' => 'button[type=submit].bricks-button',
						],
					],
				],
			],
		];
	}

	/**
	 * Get all controls for an element (element-specific + inherited).
	 *
	 * Inherited controls with elementScope are conditionally included:
	 * - "nonLayout": only for non-layout elements
	 * - "layout": only for layout elements
	 *
	 * @since 2.4
	 *
	 * @param string $element_name The element name (e.g. "heading", "button").
	 * @return array Controls indexed by control key.
	 */
	public static function get_all_element_controls( $element_name ) {
		$element_controls = self::get_element_controls();
		$element_specific = isset( $element_controls[ $element_name ] ) ? $element_controls[ $element_name ] : [];
		$controls         = $element_specific;
		$is_layout        = in_array( $element_name, self::$layout_elements, true );

		$inherited = self::get_inherited_controls();

		// Inherited controls have lower priority (element-specific override)
		foreach ( $inherited as $key => $ctrl ) {
			if ( isset( $controls[ $key ] ) ) {
				continue;
			}

			// Skip controls scoped to the wrong element type
			$scope = isset( $ctrl['elementScope'] ) ? $ctrl['elementScope'] : '';

			if ( $scope === 'nonLayout' && $is_layout ) {
				continue;
			}

			if ( $scope === 'layout' && ! $is_layout ) {
				continue;
			}

			$controls[ $key ] = $ctrl;
		}

		return $controls;
	}
}
